apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app-ingress.yaml
- booking-deployment.yaml
- booking-service.yaml
- guest-deployment.yaml
- guest-service.yaml
- hotel-webapp-deployment.yaml
- hotel-webapp-service.yaml
- room-deployment.yaml
- room-service.yaml
images:
- name: ghcr.io/nm-cicd-org/hotel-webapp
  newName: ghcr.io/nm-cicd-org/hotel-webapp
  newTag: "3"
- name: ghcr.io/nm-cicd-org/room-service
  newName: ghcr.io/nm-cicd-org/room-service
  newTag: "35"
